#!/usr/bin/env python3
"""System tray icon for Apple Studio Display 17" CRT (M7768).

Shows monitor power state in the panel. Click to toggle power.
Right-click for menu with geometry controls option.

Must run as root with access to the user's Wayland/D-Bus session.
"""

import os
import subprocess
import sys
import threading

import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk, GLib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from crt_backend import find_device, read_power, toggle_power

INSTALL_DIR = "/usr/local/lib/crt-control"
POLL_INTERVAL = 5  # seconds between power state checks


class CRTTray:
    def __init__(self, device):
        self.device = device
        self.power_on = False

        self.icon = Gtk.StatusIcon()
        self.icon.set_tooltip_text("Apple Studio Display")
        self.icon.connect("activate", self._on_click)
        self.icon.connect("popup-menu", self._on_right_click)

        self._update_icon()
        self._poll_state()

    def _update_icon(self):
        if self.power_on:
            self.icon.set_from_icon_name("video-display")
            self.icon.set_tooltip_text("Studio Display: ON")
        else:
            self.icon.set_from_icon_name("display-brightness-symbolic")
            self.icon.set_tooltip_text("Studio Display: OFF")

    def _poll_state(self):
        def check():
            state = read_power(self.device)
            new_on = (state == 1)
            if new_on != self.power_on:
                self.power_on = new_on
                GLib.idle_add(self._update_icon)
            return True

        # Initial check
        threading.Thread(target=lambda: check(), daemon=True).start()
        # Periodic polling
        GLib.timeout_add_seconds(POLL_INTERVAL, lambda: threading.Thread(target=check, daemon=True).start() or True)

    def _on_click(self, icon):
        self.power_on = not self.power_on
        self._update_icon()

        def do_toggle():
            toggle_power(self.device)

        threading.Thread(target=do_toggle, daemon=True).start()

    def _on_right_click(self, icon, button, time):
        menu = Gtk.Menu()

        toggle_item = Gtk.MenuItem(label="Toggle Power")
        toggle_item.connect("activate", lambda _: self._on_click(None))
        menu.append(toggle_item)

        geo_item = Gtk.MenuItem(label="Geometry Controls...")
        geo_item.connect("activate", self._open_gui)
        menu.append(geo_item)

        menu.append(Gtk.SeparatorMenuItem())

        quit_item = Gtk.MenuItem(label="Quit")
        quit_item.connect("activate", lambda _: Gtk.main_quit())
        menu.append(quit_item)

        menu.show_all()
        menu.popup(None, None, None, None, button, time)

    def _open_gui(self, _widget):
        gui_path = os.path.join(INSTALL_DIR, "pi-adc-gui.py")
        if not os.path.exists(gui_path):
            gui_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "pi-adc-gui.py")
        subprocess.Popen([
            "python3", gui_path
        ], env={**os.environ, "GDK_BACKEND": "wayland"})


def main():
    if os.geteuid() != 0:
        print("Must run as root.", file=sys.stderr)
        sys.exit(1)

    device = find_device()
    if not device:
        print("Apple Studio Display not found.", file=sys.stderr)
        sys.exit(1)

    CRTTray(device)
    Gtk.main()


if __name__ == "__main__":
    main()
